### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by callmekohei**
Tried to describe more details of the instruction.
Feel free to reject/modify my propose if it's not correct.

### CODE REVIEW

**Comment by Shougo** [comment]
I think it uses 9999 port.
But the README says 8080 port.

**Comment by callmekohei** [comment]
Yes, yes. I know it. I will merge carefully. (^_^)/

**Comment by Shougo** [comment]
:-)

**Comment by callmekohei** [comment]
Thank you very much for @yukitos and @Shougo !

**Pull request merged**
